#ifndef __myframe__
#define __myframe__

/**
@file
Subclass of MyFrameBase, which is generated by wxFormBuilder.
*/

#include "myformbase.h"

//// end generated include

/** Implementing MyFrameBase */
class MyFrame : public MyFrameBase
{
	public:
		/** Constructor */
		MyFrame( wxWindow* parent );
	//// end generated class members


public:
	MyFrame(wxString title, wxPoint pos, wxSize size);


};

#endif // __myframe__
