#ifndef __mypanel__
#define __mypanel__

/**
@file
Subclass of MyPanelBase, which is generated by wxFormBuilder.
*/

#include "myformbase.h"

//// end generated include

#include <vector>
#include "wx/tokenzr.h"

/** Implementing MyPanelBase */
class MyPanel : public MyPanelBase
{
	protected:
		// Handlers for MyPanelBase events.
		void onClear( wxCommandEvent& event );
		void onGenerate( wxCommandEvent& event );
	public:
		/** Constructor */
		MyPanel( wxWindow* parent );
	//// end generated class members

public:
	void setSpinCtrl();

private:
	std::vector<std::vector<double>> getValues(wxString& input);
    void setValues(std::vector<std::vector<double>>& values);
	double randomValue(double min, double max);

	double minValue{-0.001};
	double maxValue{0.001};
	
};

#endif // __mypanel__
